export default {
	login: "glenmaytum",
	id: 43425559,
	node_id: "MDQ6VXNlcjQzNDI1NTU5",
	avatar_url: "https://avatars.githubusercontent.com/u/43425559?v=4",
	gravatar_id: "",
	url: "https://api.github.com/users/glenmaytum",
	html_url: "https://github.com/glenmaytum",
	followers_url: "https://api.github.com/users/glenmaytum/followers",
	following_url:
		"https://api.github.com/users/glenmaytum/following{/other_user}",
	gists_url: "https://api.github.com/users/glenmaytum/gists{/gist_id}",
	starred_url:
		"https://api.github.com/users/glenmaytum/starred{/owner}{/repo}",
	subscriptions_url: "https://api.github.com/users/glenmaytum/subscriptions",
	organizations_url: "https://api.github.com/users/glenmaytum/orgs",
	repos_url: "https://api.github.com/users/glenmaytum/repos",
	events_url: "https://api.github.com/users/glenmaytum/events{/privacy}",
	received_events_url:
		"https://api.github.com/users/glenmaytum/received_events",
	type: "User",
	site_admin: false,
	name: null,
	company: null,
	blog: "",
	location: null,
	email: null,
	hireable: null,
	bio: null,
	twitter_username: null,
	public_repos: 28,
	public_gists: 0,
	followers: 1,
	following: 5,
	created_at: "2018-09-19T23:43:56Z",
	updated_at: "2021-07-12T21:09:42Z",
};
